Ext.define('ianMizi.model.AyohaEnterpriseAccount.AyohaEnterpriseAccountModel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            'ID'
      ,'EnterpriseAccNo'
      ,'EnterpriseName'
      ,'EnterpriseAddress'
      ,'EnterpriseRegistrationNo'
      ,'EnterpriseEmail'
      ,'EnterpriseWebsite'
      ,'EnterprisePhoneNo' 
      ,'EnterpriseDescriptions'
      ,'EnterpriseFacebook'
      ,'EnterpriseTwiter'
      ,'EnterpriseInstagram'
	  ,'EnterpriseCoordinate'
	  , 'EnterpriseLogoPath'
      ,'EnterpriseLogoName'
	   ,'RowStatus'
	   ,'CreatedDate'
      ,'CreatedBy'
      ,'ModifiedDate'
      ,'ModifiedBy'
	   ,'PICContactNo'
      ,'PersonInCharge'
      ,'LoyaltyCardType'
	   ,'EnterpriseType'
      ,'EnterpriseBusinessType'
      ,'AyohaVersion'
      ,'AyohaEnterpriseUserID'
	  ,'AccountNo'
	  ,'AccountName'
	  , 'UseName'
	  ,'Password'
	  ,'Email'
	  ,'PhoneNumber'
	  ,'Photo'
	  ,'RegisterDate'
	  ,'IsUserVerified'
	  ,'VerifyString'
	  ,'VeriyDate'
	  ,'ModifiedBy'
	  ,'ModifiedDate'
	  ,'RowActive'
	  ,'EnterpriseAccNo'
	  ,'UserType'
	  ,'UserStatus'
	  ,'LastLoginDate'
        ]
    }
});